apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app-deployment
  labels:
    app: quiz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
        - name: quiz-app
          image: ghcr.io/notsosmartdev/quiz-app:main
          imagePullPolicy: Always
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-token
                  key: BOT_TOKEN
